# CheckMeOut Configuration ${version}
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
# 
#
# Icon that will be displayed in CheckMeOut list.
# It uses native Minecraft material strings, but using string 'PLAYER_HEAD', it is possible to
# use player heads instead. Beware that Mojang API rate limiting may prevent heads from loading.
icon: 'GRASS_BLOCK'
#
# This list stores GameModes in which CheckMeOut will not apply.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
#
# CheckMeOut panel name formatting.
# Example: &c will make names red, &f is white
name-format: &f
#
# Allow random checking - adds a button to the panel that goes to a random island
random-allowed: true
#
#
# User and admin commands. You can change them if they clash with other addons or plugins.
user-command: checkmeout
admin-command: cmo
